### ISSUE TITLE
Publish nightly builds for users

### ISSUE THREAD

**Issue by ivomagi** [signalfx/splunk-otel-java#391]
In order to ease the access for end users, the published nightly builds should be linked in github repository

**Comment by breedx-splk** [comment]
@ivomagi Does #408 solve this for you?

**Comment by ivomagi** [comment]
I originally envisioned this information to be present under "Releases" (https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases), but in case this is not possible on undesirable for some reasons, good with this as well.

**Comment by mateuszrzeszutek** [comment]
Currently we release on every merge to main - that'd generate lots of noise on the "Releases" page, since you could have a few new releases everyday.

**Comment by ivomagi** [comment]
Indeed, list of all the snapshots would be noise, but if the very same information with link to snapshots that currently went to `README.md` would be present under releases maybe it would be more logical place for someone to find it?

**Comment by mateuszrzeszutek** [comment]
Hmm, we can add that text to the release notes of each release. Unfortunately GH doesn't offer a possibility to customize the page itself.

**Comment by breedx-splk** [comment]
I think that adding a link to the snapshots is not helpful and detracts from the release itself. The snapshots don't really relate to a given release anyway, so it feels awkward and forced. I think the link on the main page README should be sufficient.

Closing this because we have snapshots. Please reopen and suggest an alternative if still important.
