### ISSUE TITLE
Adding custom metric dimensions to java collector

### ISSUE THREAD

**Issue by csydvs** [signalfx/splunk-otel-java#757]
I see [here](https://docs.splunk.com/observability/gdi/get-data-in/application/java/configuration/java-otel-metrics-attributes.html) in the docs that some metrics are collected by default. However, it would be really nice if I could specify other metrics via environment variable to be passed on. Specifically, in my case, it would be super nice if I could specify the AWS task arn to be able to differentiate different tasks in my service, all of which have identical values for all of the given dimensions that are passed by default. In some cases, the otel collector would add some of these dimensions using resourcedetection, but we have the otel collector running in a different ecs service, so we can't take advantage of that easily.

**Comment by breedx-splk** [comment]
Hi @csydvs Thanks for reaching out. It sounds like you don't actually want to "specify other metrics" but that  you want to be able to add additional custom _attributes_ (like arn) to some of the existing metrics. Is that right?

I _think_ the reason this has not been built yet is that [attributes contribute to timeseries cardinality](https://github.com/open-telemetry/opentelemetry-specification/blob/90e5022a846a65600b7ad7e8d262678a83f76191/specification/metrics/datamodel.md#timeseries-model), so that every attribute contributes to the overall scale/size of the timeseries permutation space. 

For example, if you have 10 metrics with 2 attributes each (for example environment and service name), that will create 10 * N * M metrics timeseries (MTS), where N is the number of unique environments and M is the number of unique service names. If you deploy 5 hosts in 3 environments, you get 10 * 5 * 3 = 150 MTS, even if not all services are deployed in all environments. Adding another dimension (like arn or color or something) multiplies it further -- so if you have 5 arns, this balloons to 750MTS...and a week later when you add a new task it goes to 900.

This is the common problem of "high cardinality" in metric timeseries databases. It explodes quickly and, if left wide open for users to customize, can overwhelm storage mechanisms and make systems unusable. This is why most vendors have careful constraints around the number of dimensions (attributes) allowed.

I hope that's not too much explanation and I hope we can come up with a strategy to address these kinds of requests, because it won't be the last. :)

**Comment by breedx-splk** [comment]
Ok cool to hear that you found a work around. I'm going to close this issue but feel free to reopen if there's more to discuss. Thanks!
